name: Actualizar Firebase Futbol

on:
  schedule:
    # Lunes a Jueves (1-4): Cada 3 horas
    - cron: '0 */3 * * 1-4'
    
    # Viernes y Sábado (5-6): Cada hora
    - cron: '0 * * * 5-6'
    
    # Domingo (0): Cada hora
    - cron: '0 * * * 0'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usamos una versión estable y moderna

      - name: Instalar dependencias de Node
        run: npm install

      - name: Instalar Chrome para Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Ejecutar script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node index.js